#!/usr/bin/env ruby

require 'mkpassword'
require 'optparse'
require 'securerandom'

Version = Mkpassword::VERSION
params = ARGV.getopts("l:s:c:","help")

if params['help']
  puts "
Usage: #{$0} [options]
    -l length				(default:12)
    -s number of special characters  	(default:0)
    -c count				(default:1)
    -v show version

" 
  exit
end

l = params['l']&.to_i || 12
s = params['s']&.to_i || 0
c = params['c']&.to_i || 1

special_src = [*'!'..'~'] - [*'a'..'z'] - [*'A'..'Z'] - [*'0'..'9']

if (l - s) < 1 or l < 1 or c < 1
  puts 'Error'
  exit 1
end

c.times {
  alphanumerics = SecureRandom.alphanumeric(l - s).split(//)
  specialchars = s.times.map { special_src[SecureRandom.random_number(special_src.size)] }
  results = (alphanumerics + specialchars).shuffle.join
  puts results
}
